### ISSUE TITLE
Calibre returns an error if I try to open a book which title is too long

### ISSUE THREAD

**Issue by afgks** [die/calibre-rpc#12]
I have to disable this plugin before Calibre lets me view the book.

```
calibre, version 7.20.0
ERROR: Unhandled exception: <b>ServerError</b>:Child "activity" fails because child "state" fails because "state" length must be less than or equal to 128 characters long

calibre 7.20  embedded-python: True
Windows-10-10.0.26100-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.26100')
Python 3.11.5
Windows: ('10', '10.0.26100', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Calibre RPC (1, 0, 0) && FanFicFare (4, 39, 0) && KoboTouchExtended (3, 7, 0)
Traceback (most recent call last):
  File "calibre\gui2\actions\view.py", line 324, in view_triggered
  File "calibre\gui2\actions\view.py", line 401, in _view_books
  File "calibre_plugins.calibre_rpc.hooks", line 19, in _view_calibre_books
  File "calibre_plugins.calibre_rpc.rpc", line 44, in update
  File "calibre_plugins.calibre_rpc.pypresence.presence", line 32, in update
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "calibre_plugins.calibre_rpc.pypresence.baseclient", line 86, in read_output
calibre_plugins.calibre_rpc.pypresence.exceptions.ServerError: Child "activity" fails because child "state" fails because "state" length must be less than or equal to 128 characters long

```

**Comment by die** [comment]
will be fixed when i get time tomorrow, thanks for reporting

**Comment by die** [comment]
fix is in new release https://github.com/die/calibre-rpc/releases/latest
