### ISSUE TITLE
Switching to another library then opening a book causes "tuple index out of range" error

### ISSUE THREAD

**Issue by afgks** [die/calibre-rpc#15]
Disabling Calibre RPC fixes this error.

This is the error log:

```
calibre, version 7.22.0
ERROR: Unhandled exception: <b>IndexError</b>:tuple index out of range

calibre 7.22  embedded-python: True
Windows-10-10.0.26100-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.26100')
Python 3.11.5
Windows: ('10', '10.0.26100', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Calibre RPC (1, 0, 0) && FanFicFare (4, 40, 0)
Traceback (most recent call last):
  File "calibre\gui2\actions\view.py", line 324, in view_triggered
  File "calibre\gui2\actions\view.py", line 401, in _view_books
  File "calibre_plugins.calibre_rpc.hooks", line 16, in _view_calibre_books
IndexError: tuple index out of range

```

**Comment by die** [comment]
Should be fixed now with latest release, thanks!
